apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: prometheus
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.server.name }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: prometheus
spec:
  ports:
    - port: {{ .Values.server.httpPort }}
      protocol: TCP
      targetPort: 9090
  selector:
    app: {{ template "fullname" . }}
    component: "{{ .Values.server.name }}"
  type: "{{ .Values.server.serviceType }}"
